#!/bin/sh
# PreToolUse hook for Edit|Write: refuse a hand edit to a generated file.
#
# Claude Code passes the tool call as JSON on stdin; `tool_input.file_path` is
# the target. Exit 2 blocks the call and returns stderr to the model as the
# reason, so the message below is what a session sees instead of a diff.
# Anything else (no path, malformed input) exits 0 and lets the call through:
# this guard exists to stop one known mistake, not to be a second permission
# system.
#
# **The path is normalised before matching, and that is not cosmetic.** A glob
# compares text, so `web/src/api//schema.d.ts` and `web/src/api/../api/
# schema.d.ts` name the same file and miss the same pattern -- verified failing
# open on 2026-09-02, before `os.path.normpath` was added here. A relative path
# is resolved against `$CLAUDE_PROJECT_DIR` for the same reason: `Edit` supplies
# an absolute path today, so a bare `web/src/api/schema.d.ts` is not a spelling
# a session produces, but the guard should not depend on that staying true.
#
# If `python3` is missing this exits 0 and the guard is simply absent. That is
# the same fail-open as malformed input and is deliberate, but it means this
# hook is not a security boundary -- it is a reminder with teeth.
path=$(python3 -c '
import json, os, sys
try:
    raw = json.load(sys.stdin).get("tool_input", {}).get("file_path") or ""
except Exception:
    raw = ""
if raw:
    root = os.environ.get("CLAUDE_PROJECT_DIR") or "."
    print(os.path.normpath(os.path.join(root, raw)))
' 2>/dev/null) || exit 0

case "$path" in
  */web/src/api/schema.d.ts)
    cat >&2 <<'MSG'
web/src/api/schema.d.ts is generated by `npm run gen:types` against a running
server's /openapi.json; a hand edit survives only until the next run. Change
the FastAPI DTO the type comes from and regenerate (.claude/rules/console.md).
MSG
    exit 2 ;;
esac
exit 0
