"""core schema

Revision ID: 4fd67790a956
Revises:
Create Date: 2026-07-29 12:30:25.616982

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fd67790a956"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("credentials_ref", sa.Text(), nullable=False),
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("supports_push", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name="ck_sources_name_not_empty"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "titles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=16), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("genres", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("keywords", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("original_language", sa.String(length=16), nullable=True),
        sa.Column("spoken_languages", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("origin_countries", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("content_rating", sa.String(length=32), nullable=True),
        sa.Column("community_rating", sa.Float(), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("enrichment_state", sa.String(length=16), nullable=False),
        sa.Column("enrichment_error", sa.Text(), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name="ck_titles_name_not_empty"),
        sa.CheckConstraint("sort_name <> ''", name="ck_titles_sort_name_not_empty"),
        sa.CheckConstraint(
            "community_rating IS NULL OR community_rating BETWEEN 0 AND 10",
            name="ck_titles_community_rating_range",
        ),
        sa.CheckConstraint(
            "end_year IS NULL OR end_year >= 0", name="ck_titles_end_year_non_negative"
        ),
        sa.CheckConstraint(
            "popularity IS NULL OR popularity >= 0", name="ck_titles_popularity_non_negative"
        ),
        sa.CheckConstraint(
            "runtime_minutes IS NULL OR runtime_minutes >= 0",
            name="ck_titles_runtime_minutes_non_negative",
        ),
        sa.CheckConstraint(
            "vote_count IS NULL OR vote_count >= 0", name="ck_titles_vote_count_non_negative"
        ),
        sa.CheckConstraint("year IS NULL OR year >= 0", name="ck_titles_year_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_titles_enrichment_state", "titles", ["enrichment_state"], unique=False)
    op.create_index(
        "ix_titles_imdb_id",
        "titles",
        ["imdb_id"],
        unique=True,
        postgresql_where=sa.text("imdb_id IS NOT NULL"),
    )
    op.create_index("ix_titles_popularity", "titles", ["popularity"], unique=False)
    op.create_index("ix_titles_sort_name", "titles", ["sort_name"], unique=False)
    op.create_index(
        "ix_titles_tmdb_id",
        "titles",
        ["tmdb_id"],
        unique=True,
        postgresql_where=sa.text("tmdb_id IS NOT NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name="ck_users_name_not_empty"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "media_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("container", sa.String(length=32), nullable=True),
        sa.Column("video_codec", sa.String(length=32), nullable=True),
        sa.Column("audio_codec", sa.String(length=32), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("hdr_format", sa.String(length=16), nullable=True),
        sa.Column("audio_channels", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("runtime_seconds", sa.Integer(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "audio_channels IS NULL OR audio_channels >= 0",
            name="ck_media_items_audio_channels_non_negative",
        ),
        sa.CheckConstraint(
            "file_size_bytes IS NULL OR file_size_bytes >= 0",
            name="ck_media_items_file_size_bytes_non_negative",
        ),
        sa.CheckConstraint(
            "height IS NULL OR height >= 0", name="ck_media_items_height_non_negative"
        ),
        sa.CheckConstraint(
            "runtime_seconds IS NULL OR runtime_seconds >= 0",
            name="ck_media_items_runtime_seconds_non_negative",
        ),
        sa.CheckConstraint("width IS NULL OR width >= 0", name="ck_media_items_width_non_negative"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_media_items_source_external"),
    )
    op.create_index("ix_media_items_title_id", "media_items", ["title_id"], unique=False)
    op.create_index(
        "ix_media_items_unmatched",
        "media_items",
        ["source_id"],
        unique=False,
        postgresql_where=sa.text("title_id IS NULL"),
    )
    op.create_table(
        "watch_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("position_seconds", sa.Integer(), nullable=False),
        sa.Column("runtime_seconds", sa.Integer(), nullable=True),
        sa.Column("played", sa.Boolean(), nullable=False),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "num_nonnulls(title_id, episode_id) = 1", name="ck_watch_states_exactly_one_target"
        ),
        sa.CheckConstraint("play_count >= 0", name="ck_watch_states_play_count_non_negative"),
        sa.CheckConstraint(
            "position_seconds >= 0", name="ck_watch_states_position_seconds_non_negative"
        ),
        sa.CheckConstraint(
            "runtime_seconds IS NULL OR runtime_seconds >= 0",
            name="ck_watch_states_runtime_seconds_non_negative",
        ),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "episode_id", name="uq_watch_states_user_episode"),
        sa.UniqueConstraint("user_id", "title_id", name="uq_watch_states_user_title"),
    )
    op.create_index(
        "ix_watch_states_user_played", "watch_states", ["user_id", "played"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_watch_states_user_played", table_name="watch_states")
    op.drop_table("watch_states")
    op.drop_index(
        "ix_media_items_unmatched",
        table_name="media_items",
        postgresql_where=sa.text("title_id IS NULL"),
    )
    op.drop_index("ix_media_items_title_id", table_name="media_items")
    op.drop_table("media_items")
    op.drop_table("users")
    op.drop_index(
        "ix_titles_tmdb_id", table_name="titles", postgresql_where=sa.text("tmdb_id IS NOT NULL")
    )
    op.drop_index("ix_titles_sort_name", table_name="titles")
    op.drop_index("ix_titles_popularity", table_name="titles")
    op.drop_index(
        "ix_titles_imdb_id", table_name="titles", postgresql_where=sa.text("imdb_id IS NOT NULL")
    )
    op.drop_index("ix_titles_enrichment_state", table_name="titles")
    op.drop_table("titles")
    op.drop_table("sources")
    # ### end Alembic commands ###
