"""Price both suggest tiers at catalog scale, against a bar written first.

**Not a test, and not a fixture.** It reads a real database and takes the
catalog as it finds it -- it creates no title, enriches nothing, and the only
thing it writes is the two tier-1 prefix indexes it drops and rebuilds to time
them. Point it at a throwaway catalog, never at one somebody else is using.

    docker run -d --name usher-b3-pg -e POSTGRES_USER=usher \\
      -e POSTGRES_PASSWORD=usher -e POSTGRES_DB=usher -p 55434:5432 \\
      --shm-size=1g pgvector/pgvector:pg17
    export USHER_DATABASE_URL="postgresql+asyncpg://usher:usher@localhost:55434/usher"
    export USHER_SECRET_KEY="$(openssl rand -hex 32)"
    uv run alembic upgrade head
    uv run python scripts/measure_suggest_tiers.py --all

================================================================================
THE BAR -- written down, and committed, before any number was produced
================================================================================

M6's typo-tolerance gate failed its own bar on 2026-08-03 and that failure is
why tier 1 exists: the shipped trigram type-ahead finds the right title
**27.8%** of the time for a 2-4-character name and **68.3%** for 5-7, against
bars of 0.75 and 0.85; transposition on a short name is **0.0%**; and no
configuration under any threshold, cap or index type comes within **6x** of a
50 ms as-you-type budget. Above 8 characters it is 95-100% and needs nothing,
which is 91% of that catalog by row count.

This task decides whether tier 1 fixes it, so the bar goes first:

1. tier-1 p95 <= 10 ms at 1.27M titles;
2. tier-1 p95 over the union with `title_search_names` <= that same 10 ms;
3. tier-2's p50 after `m09a` is within +/-10% of the recorded **33.6 ms**, and
   its miss-diagnosis split (**63.6% below the `%` floor / 36.4% out-ranked /
   0.0% truncated by the cap / 0.0% dropped by the re-rank**) is unchanged;
4. tier-1 recall@5 on the gate's own 2,993 typo cases stays at the recorded
   **1.9%** -- a tier 1 that scores higher is not the index that was measured.

**"Tier-1 p95" is not one number, so it is three workloads and they are never
averaged together.** The gate's btree row -- p50 0.6 ms, p95 1.0 ms, max 10 ms
-- was measured over the 2,993 *typo strings*, which are whole mutated names:
long and highly selective. A keystroke is not that.

* **W1, gate-comparable.** The 2,993 typo strings as prefixes. The only
  workload whose numbers may be quoted against the gate's row, and the one
  bars (1), (2) and (4) are scored on.
* **W2, keystroke.** Prefixes of length 1..8 cut from real catalog names,
  equal draws per length, reported per length. Nothing in the gate is
  comparable to it.
* **W3, adversarial.** The single characters and two-character prefixes with
  the largest match sets. This is B2's named residual exposure -- *"a
  one-character prefix over a 1.27M-title catalog joined to
  `title_search_names`"* -- and B2 pointed it here by name.

A W1 pass with a W3 failure is a pass on bar (1) **and a reported defect**, in
that order and in those words. Tuning until a bar goes green is out of scope by
construction: if bar (2) fails, the recorded consequence is the one the plan
already names -- tier 1 scans `titles` only and `title_search_names` is
reachable from tier 2 alone.

Tolerances, fixed before the run: bar (3)'s +/-10% is 30.24 ms <= p50 <=
36.96 ms; "the split is unchanged" is each share within +/-5 points, with
**both zeros required to stay 0.0% exactly**, since a zero that moves at all is
a different finding. Bar (4)'s "stays at 1.9%" is 1.6%-2.2%.

**Bar (3)'s two halves name two different configurations and the plan pairs
them wrongly** -- found while building this harness, settled here, and settled
*before* the run rather than after seeing a number. ADR-0002's miss-diagnosis
table has a `GIN % @0.3 cap 200` row at **63.6/0/0/36.4** with p50 33.3 ms, and
a `GIN % @0.3 cap 200 + vote tiebreak` row -- the one that ships -- at
**82.8/0/0/17.2** with p50 **33.6 ms**. The bar quotes the tiebreak row's
latency and the other row's split, and `_SUGGEST` ships the tiebreak, so no
single run can satisfy both as written. The split is therefore **scored against
82.8/17.2 and reported against both**, with the plan's literal 63.6/36.4
printed beside it every time. `.claude/rules/search-and-embeddings.md` carries
the same mispairing in prose -- *"at the shipped configuration 63.6% fell below
the `%` floor"* -- and is corrected in the same commit as the number.

================================================================================
THE TYPO SET, AND WHY IT IS THE GATE'S OWN
================================================================================

Regenerated by the recorded procedure rather than restored from a file, because
**the test set is built from real catalog rows and is therefore not committed;
the measurement is.** Movies only, `vote_count >= 500`, names not unique in the
catalog excluded at sampling time, five equal draws of 150 over
`char_length(name)` bands 2-4 / 5-7 / 8-11 / 12-19 / 20+, four typo classes per
name at a uniformly random position, `random.Random(20260803)`, and 2,993 cases
rather than 3,000 because seven two-character names admit no deletion.

**The frame is verified rather than assumed**, and this is what makes the two
runs comparable at all: on the gate's catalog this procedure reproduces
**81,054** shared lower-cased names and eligible pools of **432 / 2,532 /
7,178 / 20,520 / 17,887** -- the five numbers the rules file records, to the
row. `--check-frame` prints them and refuses to go on if any differs.

What is *not* claimed: that the 750 sampled names are the same 750. The gate's
draw order was not recorded, only its procedure and its pool sizes, so a
different-but-equivalent draw is possible and every number here carries that
caveat.

================================================================================
WHAT ELSE IS RECORDED WITH EVERY NUMBER
================================================================================

The catalog's row count **and its bootstrap phase**, because
*"`popularity` IS NULL on all 1,271,138 rows"* was a `--phase imdb` fact read
as a catalog fact and it was wrong by half. The `title_search_names` row count
and its `kind` breakdown, beside every tier-1 figure, because a union over an
empty arm is not the union that ships -- and the script **refuses** to print a
union figure against an empty table.

And **whether the box was quiet, by a metric a clean run can actually pass.**
Every product of this script is a rate or a latency, so a number taken on a
loaded box is void -- but the first spelling of that guard compared the
one-minute load average before against after, which a forty-minute run of
continuous querying raises *by itself*. That guard condemns every clean run and
is a measurement of the work rather than of the box. What is read instead, at
two moments when this harness is deliberately idle, is the **foreign `pytest`
census** (this run spawns none, so any is somebody else's suite) and the
**drift** in non-idle CPU. A drift rather than a level, because this host's
always-on services idle at a baseline nobody has measured and an absolute
threshold guessed against it repeats the same mistake one level down. The load
average stays in the record as context and decides nothing.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import statistics
import time
import uuid
from collections.abc import Iterable, Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from usher.adapters.search import prefix as prefix_module
from usher.adapters.search.postgres import PostgresSuggestIndex
from usher.adapters.search.prefix import PostgresPrefixSuggestIndex
from usher.config import Settings
from usher.db.base import build_engine, build_session_factory

# The gate's own generation constants. Named rather than inlined so a reader
# can see at a glance that nothing here was re-chosen.
GATE_SEED = 20260803
GATE_BANDS: tuple[tuple[str, int, int], ...] = (
    ("2-4", 2, 4),
    ("5-7", 5, 7),
    ("8-11", 8, 11),
    ("12-19", 12, 19),
    ("20+", 20, 10_000),
)
GATE_DRAW_PER_BAND = 150
GATE_POOLS = {"2-4": 432, "5-7": 2532, "8-11": 7178, "12-19": 20520, "20+": 17887}
GATE_SHARED_LOWER_NAMES = 81_054
GATE_CASES = 2_993

# The shipped defaults, from `Settings`. Interpolated nowhere -- both cross as
# bind parameters or through the adapter's own range-checked formatter.
SHIPPED_THRESHOLD = 0.3
SHIPPED_CANDIDATES = 200

# The union arm, lifted verbatim so the titles-only variant is *derived from*
# B2's statement rather than retyped beside it. If B2's SQL is ever edited, the
# surgery finds nothing and the run refuses rather than measuring a stale copy
# of a statement that has moved.
_UNION_ARM = """    UNION
    SELECT n.title_id
    FROM title_search_names AS n
    WHERE lower(n.name) LIKE :pattern
"""

# Tier 1 with the second arm removed. **This is the artefact bar (1) is scored
# on and it is also the narrowing the plan names as bar (2)'s failure
# consequence** -- one statement serving both, so the number that would justify
# the narrowing is measured on the narrowing itself.
_TITLES_ONLY = prefix_module._PREFIX.replace(_UNION_ARM, "")

# Bands for W2. One through eight, because eight is where the gate's recall
# curve stops needing help (95.5% at 8-11) and because nobody types past it
# before the debounce fires.
KEYSTROKE_LENGTHS = tuple(range(1, 9))
KEYSTROKE_DRAWS = 100


class MeasurementRefused(RuntimeError):
    """A precondition the run will not proceed without.

    Its own class rather than a bare `RuntimeError` so the three call sites
    that raise it read as one rule: an empty table, a drifted statement and a
    drifted sampling frame are all "this would produce a plausible number that
    means nothing", which is the failure this whole script is arranged against.
    """


@dataclass(frozen=True, slots=True)
class TypoCase:
    """One mutated name, and the title it should still find."""

    title_id: uuid.UUID
    name: str
    band: str
    typo_class: str
    probe: str


@dataclass
class Timing:
    """A latency distribution and the number of observations behind it."""

    label: str
    observations: int
    p50: float
    p95: float
    maximum: float
    minimum: float
    mean: float

    @classmethod
    def of(cls, label: str, samples: Sequence[float]) -> Timing:
        ordered = sorted(samples)
        if not ordered:
            return cls(label, 0, 0.0, 0.0, 0.0, 0.0, 0.0)
        return cls(
            label=label,
            observations=len(ordered),
            p50=_quantile(ordered, 0.50),
            p95=_quantile(ordered, 0.95),
            maximum=ordered[-1],
            minimum=ordered[0],
            mean=statistics.fmean(ordered),
        )


@dataclass
class RunLog:
    """Everything the run produced, in one JSON document.

    A dict rather than prose, because the write-up quotes it and a number
    retyped from a terminal is a number nobody can re-check.
    """

    started_at: str = ""
    catalog: dict[str, Any] = field(default_factory=dict)
    search_names: dict[str, Any] = field(default_factory=dict)
    load: dict[str, Any] = field(default_factory=dict)
    indexes: dict[str, Any] = field(default_factory=dict)
    tier1: dict[str, Any] = field(default_factory=dict)
    tier2: dict[str, Any] = field(default_factory=dict)
    plans: dict[str, Any] = field(default_factory=dict)
    verdicts: dict[str, Any] = field(default_factory=dict)


def _say(message: str) -> None:
    """A progress line with a wall clock on it.

    Not decoration: a run of this measured **over half an hour** on the first
    end-to-end pass and the log was silent for all of it, so there was no way
    to tell a slow phase from a hung one -- or to size the quiet window the
    real run needs. Every phase says what it is about to do and how much of
    it there is.
    """
    print(f"[{time.strftime('%H:%M:%S')}] {message}", flush=True)


def _quantile(ordered: Sequence[float], q: float) -> float:
    """Nearest-rank quantile.

    Nearest-rank rather than interpolated, because an interpolated p95 over
    2,993 observations invents a latency no query had -- and the number this is
    compared against, the gate's 1.0 ms, came off a distribution of real
    executions.
    """
    if not ordered:
        return 0.0
    rank = max(1, min(len(ordered), int(-(-len(ordered) * q // 1))))
    return ordered[rank - 1]


# How long `_cpu_busy` samples for, and how far the busy fraction may drift
# across a run before the run is thrown away. Both are declared here, before
# any number, because a threshold chosen after seeing a result is not a
# threshold.
_CPU_SAMPLE_SECONDS = 2.0
_CPU_DRIFT_LIMIT = 0.10
# Let the box settle after the last backend closes, so the closing sample is
# taken under the same condition as the opening one rather than in this run's
# own wake.
_CPU_SETTLE_SECONDS = 5.0


def _cpu_counters() -> tuple[int, int]:
    """`/proc/stat`'s aggregate jiffies as (total, idle-including-iowait)."""
    fields = [int(one) for one in Path("/proc/stat").read_text().split("\n")[0].split()[1:]]
    return sum(fields), fields[3] + fields[4]


def _cpu_busy(seconds: float = _CPU_SAMPLE_SECONDS) -> float:
    """The fraction of all CPU that is *not* idle, over `seconds`.

    **Sampled while this script is deliberately doing nothing**, which is the
    whole point: taken at a moment when the harness is idle, every busy jiffy
    belongs to somebody else. That is what makes it a measurement of the box
    rather than a measurement of the run.
    """
    first_total, first_idle = _cpu_counters()
    time.sleep(seconds)
    second_total, second_idle = _cpu_counters()
    elapsed = second_total - first_total
    if elapsed <= 0:
        return 0.0
    return round(1.0 - (second_idle - first_idle) / elapsed, 4)


def _load_snapshot() -> dict[str, Any]:
    """What *else* the box was doing, read rather than assumed.

    **This replaces a load-average check that a good run was guaranteed to
    fail, and the replacement was made before the run rather than after it.**
    The bar says a run taken on a moving box is discarded and not caveated. The
    first spelling of that compared the one-minute load average before and
    after -- but the run is forty minutes of continuous querying whose worst
    probes go parallel, so a perfectly quiet box ends it two to three above
    where it started, *entirely from this script's own work*, and the guard
    then condemns the very measurement it exists to protect. A metric a clean
    run must fail is not measuring quiet, it is measuring that the work
    happened.

    So the two things that are read now are read at moments when the harness is
    idle, and one of them is a drift rather than a level:

    * **`pytest` processes**, which this run never spawns, so any is foreign
      and a sibling suite is exactly the named noise source; and
    * **the non-idle CPU fraction**, compared before against after. A *drift*
      rather than an absolute, because the always-on services on this host
      (Home Assistant, vLLM, ComfyUI, a reverse proxy) idle at some unknown
      baseline, and an absolute threshold guessed against that baseline is the
      same self-inflicted failure one level down.

    The load average stays in the record as context. It is no longer the gate.
    """
    one, five, fifteen = os.getloadavg()
    procs = {"postgres": 0, "pytest": 0, "python": 0}
    for entry in Path("/proc").iterdir():
        if not entry.name.isdigit():
            continue
        try:
            command = (entry / "cmdline").read_bytes().decode("utf-8", "replace")
        except OSError:
            continue
        if not command:
            continue
        for key in procs:
            if key in command:
                procs[key] += 1
    return {
        "loadavg": [one, five, fifteen],
        "processes": procs,
        "cpus": os.cpu_count(),
        "cpu_busy": _cpu_busy(),
    }


async def _scalar(session: AsyncSession, statement: str, **parameters: Any) -> Any:
    return (await session.execute(text(statement), parameters)).scalar()


async def catalog_facts(session: AsyncSession) -> dict[str, Any]:
    """Size, phase and the three columns every conclusion here depends on."""
    row = (
        await session.execute(
            text(
                """
                SELECT count(*) AS titles,
                       count(*) FILTER (WHERE popularity IS NOT NULL) AS with_popularity,
                       count(*) FILTER (WHERE vote_count IS NOT NULL) AS with_vote_count,
                       count(*) FILTER (WHERE kind = 'movie') AS movies,
                       count(*) FILTER (WHERE enrichment_state <> 'skeleton') AS enriched
                FROM titles
                """
            )
        )
    ).one()
    facts = dict(row._mapping)
    # **The phase is inferred and says so.** `link_crosswalk` is the only
    # writer of `popularity` on a bootstrap-only catalog, so a catalog with
    # none has not seen `--phase crosswalk|all`. That inference is exactly the
    # one M6 got wrong in the other direction, so it is labelled as an
    # inference every time it is printed.
    facts["phase_inferred"] = "imdb" if facts["with_popularity"] == 0 else "crosswalk-or-all"
    return facts


async def search_name_facts(session: AsyncSession) -> dict[str, Any]:
    """`title_search_names`' size and which of its two arms holds it."""
    rows = (
        await session.execute(
            text(
                "SELECT kind, count(*) AS rows, count(DISTINCT title_id) AS titles "
                "FROM title_search_names GROUP BY kind ORDER BY kind"
            )
        )
    ).all()
    by_kind = {row.kind: {"rows": row.rows, "titles": row.titles} for row in rows}
    total = sum(one["rows"] for one in by_kind.values())
    return {
        "rows": total,
        "by_kind": by_kind,
        # Said out loud on every run: B1 landed `person`, T7 owes `alias`.
        "arms_present": sorted(by_kind),
        "arms_absent": sorted({"alias", "person"} - set(by_kind)),
    }


async def check_frame(session: AsyncSession) -> dict[str, Any]:
    """The gate's sampling frame, reproduced or refused.

    Five numbers, and all five have to land. A pool that is one row out is a
    different eligible population, and a recall figure taken over a different
    population is not the gate's figure however close it looks.
    """
    shared = await _scalar(
        session,
        "SELECT count(*) FROM (SELECT lower(name) FROM titles "
        "GROUP BY 1 HAVING count(*) > 1) AS shared",
    )
    pools: dict[str, int] = {}
    for band, low, high in GATE_BANDS:
        pools[band] = await _scalar(
            session,
            """
            SELECT count(*) FROM titles t
            WHERE t.kind = 'movie' AND t.vote_count >= 500
              AND char_length(t.name) BETWEEN :low AND :high
              AND NOT EXISTS (
                  SELECT 1 FROM titles o
                  WHERE lower(o.name) = lower(t.name) AND o.id <> t.id
              )
            """,
            low=low,
            high=high,
        )
    observed = {"shared_lower_names": shared, "pools": pools}
    if shared != GATE_SHARED_LOWER_NAMES or pools != GATE_POOLS:
        raise MeasurementRefused(
            "the sampling frame does not reproduce the gate's -- expected "
            f"{GATE_SHARED_LOWER_NAMES} shared names and pools {GATE_POOLS}, observed {observed}. "
            "Every recall number below would be over a different population."
        )
    return observed


def _mutate(name: str, typo_class: str, chooser: random.Random) -> str | None:
    """One single-edit typo of `name`, or `None` where the class does not apply.

    The four classes ADR-0002 named, at a uniformly random position. Deletion
    is the one that can decline: a two-character name deleted is a
    one-character name, which is not a case about typo tolerance.

    **A transposition draws from the positions that transpose to something
    else, and the case count is what says so.** The first spelling here drew a
    position uniformly and declined when the two characters matched, which
    produced **2,964** cases against the gate's 2,993 -- 29 short, all of them
    names holding a doubled letter at the drawn position. The gate's own
    arithmetic is `3000 - 7`, and the seven are the two-character names that
    admit no deletion, so its transposition arm declined nothing. Declining is
    not the alternative to be preferred either way: the *other* way to reach
    3,000 is to emit the unmutated name, which is a guaranteed hit for any
    index and would have made the 2-4 band's measured **0.0%** arithmetically
    impossible. Drawing from the valid positions is the only reading that
    produces both numbers.
    """
    length = len(name)
    if typo_class == "substitution":
        at = chooser.randrange(length)
        replacement = chooser.choice("abcdefghijklmnopqrstuvwxyz")
        if replacement == name[at].lower():
            replacement = "z" if replacement != "z" else "q"
        return name[:at] + replacement + name[at + 1 :]
    if typo_class == "deletion":
        if length <= 2:
            return None
        at = chooser.randrange(length)
        return name[:at] + name[at + 1 :]
    if typo_class == "transposition":
        positions = [one for one in range(length - 1) if name[one] != name[one + 1]]
        if not positions:
            return None
        at = chooser.choice(positions)
        return name[:at] + name[at + 1] + name[at] + name[at + 2 :]
    if typo_class == "doubled":
        at = chooser.randrange(length)
        return name[:at] + name[at] + name[at:]
    raise ValueError(f"unknown typo class {typo_class}")


async def build_typo_cases(session: AsyncSession) -> list[TypoCase]:
    """The gate's 2,993, regenerated from the catalog by its recorded procedure."""
    # `random.Random(20260803)` is the gate's own seed. Reproducibility is the
    # entire point of it -- a cryptographic generator here would make the two
    # runs incomparable, which is the defect S311 would be preventing if this
    # were a token.
    chooser = random.Random(GATE_SEED)  # noqa: S311
    cases: list[TypoCase] = []
    for band, low, high in GATE_BANDS:
        rows = (
            await session.execute(
                text(
                    """
                    SELECT t.id, t.name FROM titles t
                    WHERE t.kind = 'movie' AND t.vote_count >= 500
                      AND char_length(t.name) BETWEEN :low AND :high
                      AND NOT EXISTS (
                          SELECT 1 FROM titles o
                          WHERE lower(o.name) = lower(t.name) AND o.id <> t.id
                      )
                    ORDER BY t.id
                    """
                ),
                {"low": low, "high": high},
            )
        ).all()
        # Clamped only so a smoke run against a toy catalog can exercise this
        # function at all. On the real catalog every pool is larger than 150
        # and `check_frame` has already refused if it is not, so the clamp is
        # unreachable there -- which is the only condition under which a clamp
        # like this is not quietly redefining the measurement.
        drawn = chooser.sample(list(rows), min(GATE_DRAW_PER_BAND, len(rows)))
        for row in drawn:
            for typo_class in ("substitution", "deletion", "transposition", "doubled"):
                probe = _mutate(row.name, typo_class, chooser)
                if probe is None:
                    continue
                cases.append(
                    TypoCase(
                        title_id=row.id,
                        name=row.name,
                        band=band,
                        typo_class=typo_class,
                        probe=probe,
                    )
                )
    return cases


async def keystroke_probes(session: AsyncSession, chooser: random.Random) -> list[tuple[int, str]]:
    """W2: real names cut at 1..8 characters, equal draws per length."""
    rows = (
        await session.execute(
            text(
                "SELECT t.name FROM titles t WHERE t.kind = 'movie' AND t.vote_count >= 500 "
                "AND char_length(t.name) >= 8 ORDER BY t.id"
            )
        )
    ).all()
    names = [row.name for row in rows]
    probes: list[tuple[int, str]] = []
    for length in KEYSTROKE_LENGTHS:
        # **Deduplicated within a length, and that is not a saving.** At length
        # one the whole probe space is about thirty characters, so a hundred
        # draws is the same twenty strings over and over -- timing them
        # repeatedly weights the distribution by how common an initial letter
        # is rather than measuring the tail, which is exactly the wrong
        # weighting for a p95 whose job is to find the slow keystroke.
        drawn = {name[:length] for name in chooser.sample(names, min(KEYSTROKE_DRAWS, len(names)))}
        probes.extend((length, one) for one in sorted(drawn))
    return probes


async def _prefix_histogram(session: AsyncSession, table: str, width: int) -> dict[str, int]:
    """How many rows of `table` each `width`-character opening prefix matches.

    One `GROUP BY` rather than 700 `count(*)`s. Equivalent to `LIKE 'ab%'` on
    the lower-cased name for exactly the alphabet W3 draws from, which is why
    that alphabet holds no `LIKE` metacharacter: `substring` does not escape
    and `_pattern` does, and the two agree only where there is nothing to
    escape.
    """
    rows = (
        await session.execute(
            text(
                f"SELECT substring(lower(name), 1, {int(width)}) AS opening, count(*) AS rows "  # noqa: S608
                f"FROM {table} GROUP BY 1"
            )
        )
    ).all()
    await session.rollback()
    return {row.opening: row.rows for row in rows}


# Memoised for two reasons and only one of them is the four full `GROUP BY`
# scans over 10.9M rows it saves. The other is comparability: the titles-only
# and union configurations have to be timed on the *same* worst-case probes,
# and re-deriving them per configuration is one `ANALYZE` away from silently
# not being the same list.
_ADVERSARIAL: list[tuple[str, int, int]] = []


async def adversarial_probes(session: AsyncSession, top: int = 5) -> list[tuple[str, int, int]]:
    """W3: the prefixes with the largest match sets, found rather than guessed.

    One and two characters, ranked by how many rows each actually matches over
    both arms -- the worst case B2 named, chosen by measurement rather than by
    picking `t` and hoping.
    """
    if _ADVERSARIAL:
        return _ADVERSARIAL
    alphabet = set("abcdefghijklmnopqrstuvwxyz0123456789 ")
    sized: list[tuple[str, int, int]] = []
    for width in (1, 2):
        titles = await _prefix_histogram(session, "titles", width)
        names = await _prefix_histogram(session, "title_search_names", width)
        for opening in set(titles) | set(names):
            if len(opening) != width or not set(opening) <= alphabet or opening.strip() == "":
                continue
            sized.append((opening, titles.get(opening, 0), names.get(opening, 0)))
    ones = sorted((one for one in sized if len(one[0]) == 1), key=lambda one: -(one[1] + one[2]))
    twos = sorted((one for one in sized if len(one[0]) == 2), key=lambda one: -(one[1] + one[2]))
    _ADVERSARIAL.extend(ones[:top] + twos[:top])
    return _ADVERSARIAL


# A probe's timed executions are capped by a wall-clock budget as well as by
# `--reps`, and the cap is what makes W3 runnable at all: a one-character
# prefix over 1.27M titles unioned with 10.9M names is not a 2 ms query, and
# five repetitions of a hundred such probes is an hour. Never fewer than three,
# because two observations do not have a p95 worth printing.
_PROBE_BUDGET_MS = 3_000.0
_MIN_REPS = 3

# **W3's second configuration, and the reason it exists is that the first one
# flatters the union.** The worst-case plan is a Gather with two workers
# (`loops=3`), so a one-character union probe is being timed *with two spare
# cores thrown at it on an otherwise idle box* -- and a type-ahead surface is
# concurrent by definition. The cores that make the parallel figure what it is
# are exactly the cores that will not be free when many people are typing. Left
# alone, this harness would have produced a best case for the union and labelled
# it the union's cost.
#
# `SET LOCAL`, never `SET`, for the reason `PostgresSuggestIndex` gives about
# `pg_trgm.similarity_threshold`: the other spelling writes the pooled session
# and one probe's setting would govern the next unrelated one. It is issued
# *outside* the timed region but inside the same transaction, so the round trip
# is not charged to the query and the rollback after each execution discards it.
#
# **W3 only.** W1 and W2 are not Gather-shaped at their sub-millisecond
# latencies, they are what bars (1) and (2) are scored on, and widening this
# would put two variables in one window.
_NO_PARALLEL = "SET LOCAL max_parallel_workers_per_gather = 0"


async def _time_statement(
    session: AsyncSession,
    statement: str,
    probe: str,
    limit: int,
    reps: int,
    *,
    serial: bool = False,
) -> list[float]:
    """Timed executions in milliseconds, after one discarded warm-up.

    The warm-up is discarded *and* read: it is what decides how many
    repetitions the probe can afford, so a slow probe is measured fewer times
    rather than a fast probe being measured too few.

    `serial=True` forbids parallel workers for the duration of each execution's
    own transaction -- the floor a busy box gives you, against the ceiling an
    idle one does.
    """
    parameters = {"pattern": prefix_module._pattern(probe.lower()), "limit": limit}

    async def _once() -> float:
        if serial:
            await session.execute(text(_NO_PARALLEL))
        started = time.perf_counter()
        (await session.execute(text(statement), parameters)).all()
        elapsed = (time.perf_counter() - started) * 1000.0
        await session.rollback()
        return elapsed

    warmup = await _once()
    affordable = int(_PROBE_BUDGET_MS // max(warmup, 0.001))
    return [await _once() for _ in range(max(_MIN_REPS, min(reps, affordable)))]


async def _time_cold(
    session: AsyncSession, statement: str, probes: Iterable[str], limit: int
) -> list[float]:
    """One execution per probe, which is the shape the gate's row was measured in."""
    samples: list[float] = []
    for probe in probes:
        parameters = {"pattern": prefix_module._pattern(probe.lower()), "limit": limit}
        started = time.perf_counter()
        (await session.execute(text(statement), parameters)).all()
        samples.append((time.perf_counter() - started) * 1000.0)
        await session.rollback()
    return samples


async def _explain(
    session: AsyncSession, statement: str, probe: str, limit: int, *, serial: bool = False
) -> str:
    parameters = {"pattern": prefix_module._pattern(probe.lower()), "limit": limit}
    if serial:
        await session.execute(text(_NO_PARALLEL))
    rows = (
        await session.execute(text(f"EXPLAIN (ANALYZE, BUFFERS) {statement}"), parameters)
    ).all()
    await session.rollback()
    return "\n".join(row[0] for row in rows)


async def verify_harness(session: AsyncSession, log: RunLog) -> None:
    """Three checks that make the numbers below mean what they say.

    The first two are about the *statement*: that the titles-only variant is
    B2's own SQL minus one arm rather than a retyped near-copy, and that the
    surgery actually removed something. The third is about the *adapter*: that
    executing the shipped constant directly agrees, row for row, with driving
    `PostgresPrefixSuggestIndex.suggest`. Without it this script measures a
    copy of the shipped path and reports it as the shipped path.
    """
    if prefix_module._PREFIX.count(_UNION_ARM) != 1:
        raise MeasurementRefused(
            "B2's `_PREFIX` no longer contains the union arm verbatim, so the titles-only "
            "variant could not be derived from it. Re-derive it before measuring anything."
        )
    if "title_search_names" in _TITLES_ONLY:
        raise MeasurementRefused("the titles-only variant still reads `title_search_names`")
    adapter = PostgresPrefixSuggestIndex(session)
    checks: list[dict[str, Any]] = []
    for probe in ("the", "a", "star w"):
        through_adapter = [one.title_id for one in await adapter.suggest(probe, limit=10)]
        direct = [
            row.id
            for row in (
                await session.execute(
                    text(prefix_module._PREFIX),
                    {"pattern": prefix_module._pattern(probe.lower()), "limit": 10},
                )
            ).all()
        ]
        if through_adapter != direct:
            raise MeasurementRefused(
                f"driving the adapter and executing its statement disagree on {probe!r}"
            )
        checks.append({"probe": probe, "rows": len(direct)})
    await session.rollback()
    log.verdicts["harness_checks"] = checks


async def measure_indexes(session: AsyncSession) -> dict[str, Any]:
    """Build time and size for both prefix indexes, dropped and rebuilt to time them.

    Against the gate's **0.559 s / 44 MB** for the `titles` one. The second has
    no prior number at all, which is the point: `title_search_names` did not
    exist when the gate ran.
    """
    result: dict[str, Any] = {}
    for name, table, expression in (
        ("ix_titles_name_lower_prefix", "titles", "lower(name) text_pattern_ops"),
        (
            "ix_title_search_names_name_lower_prefix",
            "title_search_names",
            "lower(name) text_pattern_ops",
        ),
    ):
        rows = await _scalar(session, f"SELECT count(*) FROM {table}")  # noqa: S608
        await session.execute(text(f"DROP INDEX IF EXISTS {name}"))
        await session.commit()
        started = time.perf_counter()
        await session.execute(text(f"CREATE INDEX {name} ON {table} USING btree ({expression})"))
        await session.commit()
        build_seconds = time.perf_counter() - started
        size = await _scalar(session, "SELECT pg_relation_size(:name)", name=name)
        result[name] = {
            "table": table,
            "table_rows": rows,
            "build_seconds": round(build_seconds, 3),
            "size_bytes": size,
            "size_mb": round(size / 1024 / 1024, 1),
        }
        await session.execute(text(f"ANALYZE {table}"))
        await session.commit()
    return result


async def measure_tier1(
    session: AsyncSession,
    cases: Sequence[TypoCase],
    log: RunLog,
    *,
    reps: int,
    with_union: bool,
) -> dict[str, Any]:
    """W1, W2 and W3 for one arm configuration."""
    label = "union" if with_union else "titles-only"
    statement = prefix_module._PREFIX if with_union else _TITLES_ONLY
    names = await search_name_facts(session)
    if with_union and names["rows"] == 0:
        raise MeasurementRefused(
            "`title_search_names` is empty, so a union figure would be a measurement of an "
            "empty relation. Seed the person arm (or run `usher derive` over an enriched "
            "catalog) before asking for bar (2)."
        )
    out: dict[str, Any] = {"search_names": names}

    probes = [one.probe for one in cases]
    _say(f"tier1 {label}: W1 cold, {len(probes)} probes")
    out["w1_cold"] = asdict(
        Timing.of(f"W1 cold ({label})", await _time_cold(session, statement, probes, 10))
    )
    _say(f"tier1 {label}: W1 warm, {len(probes)} probes x<={reps}")
    warm: list[float] = []
    for probe in probes:
        warm.extend(await _time_statement(session, statement, probe, 10, reps))
    out["w1_warm"] = asdict(Timing.of(f"W1 warm x{reps} ({label})", warm))

    chooser = random.Random(GATE_SEED)  # noqa: S311 - a fixed draw, not a secret
    by_length: dict[int, list[float]] = {length: [] for length in KEYSTROKE_LENGTHS}
    keystrokes = await keystroke_probes(session, chooser)
    _say(f"tier1 {label}: W2, {len(keystrokes)} distinct probes over lengths 1-8")
    for length, probe in keystrokes:
        by_length[length].extend(await _time_statement(session, statement, probe, 10, reps))
    out["w2"] = {
        str(length): asdict(Timing.of(f"W2 len={length} ({label})", samples))
        for length, samples in by_length.items()
    }
    out["w2_all"] = asdict(
        Timing.of(f"W2 all ({label})", [one for samples in by_length.values() for one in samples])
    )

    worst: dict[str, Any] = {}
    adversarial = await adversarial_probes(session)
    _say(f"tier1 {label}: W3, {len(adversarial)} worst-case probes, parallel and serial")
    for probe, title_rows, name_rows in adversarial:
        samples = await _time_statement(session, statement, probe, 10, reps)
        serial_samples = await _time_statement(session, statement, probe, 10, reps, serial=True)
        parallel = asdict(Timing.of(f"W3 {probe!r} ({label})", samples))
        serial = asdict(Timing.of(f"W3 {probe!r} serial ({label})", serial_samples))
        worst[probe] = {
            "matched_titles": title_rows,
            "matched_search_names": name_rows,
            **parallel,
            "serial": serial,
            "serial_over_parallel": (
                round(serial["p95"] / parallel["p95"], 3) if parallel["p95"] else None
            ),
        }
    out["w3"] = worst
    if worst:
        slowest = max(worst, key=lambda one: worst[one]["p95"])
        parallel_plan = await _explain(session, statement, slowest, 10)
        serial_plan = await _explain(session, statement, slowest, 10, serial=True)
        # **The knob is verified to have landed, not assumed.** `SET LOCAL` on a
        # GUC that does not exist raises, but one that exists and is scoped to
        # the wrong transaction succeeds and changes nothing -- and a serial
        # figure that is really a second parallel figure is indistinguishable
        # from a finding that parallelism does not matter here. A plant that did
        # not land looks exactly like a check that passed, so the two plans are
        # read: `Gather` must be in the first and absent from the second.
        gather_parallel = "Gather" in parallel_plan
        gather_serial = "Gather" in serial_plan
        if gather_parallel and gather_serial:
            raise MeasurementRefused(
                f"`{_NO_PARALLEL}` did not take -- the serial plan for {slowest!r} still "
                "contains a Gather, so the serial column would be a second parallel column."
            )
        log.plans[f"w3_worst_{label}"] = {
            "probe": slowest,
            "plan": parallel_plan,
            "serial_plan": serial_plan,
            "gather_in_parallel_plan": gather_parallel,
            "gather_in_serial_plan": gather_serial,
            # Said rather than implied: if the planner never chose a Gather for
            # this probe, the two columns are two measurements of one thing and
            # the parallel-assist question is answered "it does not arise here".
            "parallelism_was_in_play": gather_parallel,
        }
    return out


async def driver_floor(session: AsyncSession, reps: int) -> dict[str, Any]:
    """`SELECT 1` through the identical path, so the overhead is a number too.

    Tier 1's gate figure is 0.6 ms and a `BEGIN` is not free, so a reader
    otherwise cannot tell how much of a tier-1 latency is the index and how
    much is the driver, the transaction and SQLAlchemy's result assembly. Every
    tier-1 number here is measured the way a request pays for it -- one
    transaction per probe, timed at the Python call boundary -- and this is
    what that costs when the query does nothing at all.
    """
    samples: list[float] = []
    for index in range(reps + 1):
        started = time.perf_counter()
        (await session.execute(text("SELECT 1"))).all()
        elapsed = (time.perf_counter() - started) * 1000.0
        if index:
            samples.append(elapsed)
        await session.rollback()
    return asdict(Timing.of("driver floor (SELECT 1)", samples))


async def measure_tier1_recall(
    session: AsyncSession, cases: Sequence[TypoCase], *, with_union: bool
) -> dict[str, Any]:
    """Bar (4): recall@5, scored the way the gate scored it."""
    statement = prefix_module._PREFIX if with_union else _TITLES_ONLY
    hits = 0
    per_band: dict[str, list[int]] = {band: [] for band, _low, _high in GATE_BANDS}
    for case in cases:
        rows = (
            await session.execute(
                text(statement),
                {"pattern": prefix_module._pattern(case.probe.lower()), "limit": 5},
            )
        ).all()
        found = int(any(row.id == case.title_id for row in rows))
        hits += found
        per_band[case.band].append(found)
        await session.rollback()
    return {
        "cases": len(cases),
        "recall_at_5": round(hits / len(cases), 4) if cases else 0.0,
        "by_band": {
            band: round(sum(marks) / len(marks), 4) for band, marks in per_band.items() if marks
        },
    }


async def measure_tier2(
    session: AsyncSession, cases: Sequence[TypoCase], log: RunLog, *, diagnose: int
) -> dict[str, Any]:
    """Bar (3): the shipped tier-2 path, verbatim, plus the miss split."""
    index = PostgresSuggestIndex(
        session, threshold=SHIPPED_THRESHOLD, candidates=SHIPPED_CANDIDATES
    )
    _say(f"tier2: the shipped path over {len(cases)} cases")
    samples: list[float] = []
    hits = 0
    misses: list[TypoCase] = []
    per_band: dict[str, list[int]] = {band: [] for band, _low, _high in GATE_BANDS}
    for case in cases:
        started = time.perf_counter()
        found = await index.suggest(case.probe, limit=5)
        samples.append((time.perf_counter() - started) * 1000.0)
        marked = int(any(one.title_id == case.title_id for one in found))
        hits += marked
        per_band[case.band].append(marked)
        if not marked:
            misses.append(case)
        await session.rollback()
    _say(f"tier2: tracing {min(len(misses), diagnose)} of {len(misses)} misses to a stage")
    split = await _diagnose_misses(session, misses[:diagnose])
    log.plans["tier2_worst"] = {
        "probe": cases[samples.index(max(samples))].probe,
        "latency_ms": round(max(samples), 3),
    }
    return {
        "cases": len(cases),
        "recall_at_5": round(hits / len(cases), 4) if cases else 0.0,
        "by_band": {
            band: round(sum(marks) / len(marks), 4) for band, marks in per_band.items() if marks
        },
        "latency": asdict(Timing.of("tier 2 (shipped)", samples)),
        "misses": len(misses),
        "miss_split": split,
    }


async def _diagnose_misses(session: AsyncSession, misses: Sequence[TypoCase]) -> dict[str, Any]:
    """Trace each miss back to the stage that lost it.

    The gate's four stages, and the order they are tested in is the order the
    statement applies them, so a case is attributed to the *first* thing that
    lost it rather than to the last thing that would have.
    """
    counts = {"below_floor": 0, "truncated_by_cap": 0, "dropped_by_rerank": 0, "out_ranked": 0}
    for case in misses:
        await session.execute(
            text(f"SET LOCAL pg_trgm.similarity_threshold = {SHIPPED_THRESHOLD:.6f}")
        )
        matched = await _scalar(
            session,
            "SELECT count(*) FROM titles t WHERE t.id = :id AND t.name % :prefix",
            id=case.title_id,
            prefix=case.probe,
        )
        if not matched:
            counts["below_floor"] += 1
            await session.rollback()
            continue
        in_candidates = await _scalar(
            session,
            """
            WITH candidates AS MATERIALIZED (
                SELECT t.id FROM titles AS t
                WHERE t.name % :prefix
                ORDER BY similarity(t.name, :prefix) DESC, t.id
                LIMIT :candidates
            )
            SELECT count(*) FROM candidates WHERE id = :id
            """,
            prefix=case.probe,
            candidates=SHIPPED_CANDIDATES,
            id=case.title_id,
        )
        if not in_candidates:
            counts["truncated_by_cap"] += 1
            await session.rollback()
            continue
        survived = await _scalar(
            session,
            """
            SELECT count(*) FROM titles AS t
            WHERE t.id = :id
              AND levenshtein_less_equal(
                      left(lower(t.name), least(char_length(:prefix), 255)),
                      left(lower(:prefix), 255), 2) <= 2
            """,
            id=case.title_id,
            prefix=case.probe,
        )
        counts["out_ranked" if survived else "dropped_by_rerank"] += 1
        await session.rollback()
    total = sum(counts.values()) or 1
    return {
        "sampled": len(misses),
        "counts": counts,
        "shares": {key: round(value / total, 4) for key, value in counts.items()},
    }


def _verdicts(log: RunLog) -> dict[str, Any]:
    """The four bars, scored against the tolerances fixed above."""
    out: dict[str, Any] = {}
    titles_only = log.tier1.get("titles_only", {})
    union = log.tier1.get("union", {})

    def _bar1(source: dict[str, Any], key: str) -> dict[str, Any]:
        if not source:
            return {"verdict": "NOT MEASURED"}
        cold = source["w1_cold"]["p95"]
        warm = source["w1_warm"]["p95"]
        scored = max(cold, warm)
        return {
            "w1_p95_cold_ms": round(cold, 3),
            "w1_p95_warm_ms": round(warm, 3),
            "scored_on_ms": round(scored, 3),
            "bar_ms": 10.0,
            "verdict": "PASS" if scored <= 10.0 else "FAIL",
            "w2_p95_ms": round(source["w2_all"]["p95"], 3),
            "w2_len1_p95_ms": round(source["w2"]["1"]["p95"], 3),
            # **Both, side by side, never one replacing the other.** The
            # parallel figure is true of an idle box and is the honest ceiling;
            # the serial figure is the floor a busy box gives you. The W3
            # judgement -- which is *not* bar (1) or (2), both of which are
            # scored on W1 -- is read against the **serial** number, because the
            # question W3 asks is whether this can serve a keystroke on a box
            # that is also serving other people's keystrokes, and spare workers
            # are precisely what a concurrent type-ahead surface does not have.
            "w3_worst_p95_parallel_ms": round(max(one["p95"] for one in source["w3"].values()), 3),
            "w3_worst_p95_serial_ms": round(
                max(one["serial"]["p95"] for one in source["w3"].values()), 3
            ),
            "w3_scored_on": "serial",
            "note": f"scored on W1 only; W2/W3 reported separately for {key}",
        }

    out["bar1_tier1_titles_only"] = _bar1(titles_only, "titles-only")
    out["bar2_tier1_union"] = _bar1(union, "union")
    tier2 = log.tier2
    if tier2:
        p50 = tier2["latency"]["p50"]
        shares = tier2["miss_split"]["shares"]

        def _split(below: float, ranked: float) -> bool:
            return (
                abs(shares["below_floor"] - below) <= 0.05
                and abs(shares["out_ranked"] - ranked) <= 0.05
                and shares["truncated_by_cap"] == 0.0
                and shares["dropped_by_rerank"] == 0.0
            )

        # **Bar (3)'s two halves name two different configurations, which the
        # plan pairs wrongly, and the reconciliation is decided here rather
        # than after seeing a number.** ADR-0002's table has a `@0.3 cap 200`
        # row at 63.6/36.4 and p50 33.3 ms, and a `@0.3 cap 200 + vote
        # tiebreak` row at 82.8/17.2 and p50 **33.6 ms**. The plan quotes the
        # tiebreak row's p50 and the other row's split. `_SUGGEST` ships the
        # tiebreak, so the split it can reproduce is 82.8/17.2 -- scored on
        # that, reported against both, and the plan's literal figure printed
        # beside it every time so the reader can see which one was matched.
        # `.claude/rules/search-and-embeddings.md` carries the same pairing in
        # prose and is corrected in the same commit as this number.
        split_shipped = _split(0.828, 0.172)
        split_plan = _split(0.636, 0.364)
        out["bar3_tier2"] = {
            "p50_ms": round(p50, 3),
            "split_scored_against": "GIN % @0.3 cap 200 + vote tiebreak (82.8/0/0/17.2)",
            "split_verdict_vs_shipped": "PASS" if split_shipped else "FAIL",
            "split_verdict_vs_plans_literal_63_6": "PASS" if split_plan else "FAIL",
            "zeros_hold": shares["truncated_by_cap"] == 0.0 and shares["dropped_by_rerank"] == 0.0,
            "window_ms": [30.24, 36.96],
            "p50_verdict": "PASS" if 30.24 <= p50 <= 36.96 else "FAIL",
            "shares": shares,
            "split_verdict": "PASS" if split_shipped else "FAIL",
            "tier2_recall_at_5": tier2["recall_at_5"],
        }
    ab = log.tier2.get("without_prefix_indexes")
    if ab:
        with_indexes = log.tier2["latency"]["p50"]
        without = ab["latency"]["p50"]
        # **Within-run, over the identical 2,993 cases, with only the two
        # indexes differing.** Comparing today's p50 to the gate's 33.6 ms is
        # a comparison across two days, two runs and two levels of box
        # contention; this one has a single variable. The GIN/GiST finding is
        # the reason it exists at all -- an added index took the identical
        # configuration 33.3 -> 141.5 ms p50 for byte-identical recall, and no
        # plan-shape test could see it.
        out["btree_does_not_tax_tier2"] = {
            "p50_with_prefix_indexes_ms": round(with_indexes, 3),
            "p50_without_ms": round(without, 3),
            "ratio": round(with_indexes / without, 3) if without else None,
            "recall_identical": ab["recall_at_5"] == log.tier2["recall_at_5"],
            "verdict": "PASS" if without and abs(with_indexes / without - 1.0) <= 0.10 else "FAIL",
        }
    recall = log.tier1.get("recall", {})
    if recall:
        value = recall["recall_at_5"]
        out["bar4_tier1_recall"] = {
            "recall_at_5": value,
            "window": [0.016, 0.022],
            "verdict": "PASS" if 0.016 <= value <= 0.022 else "FAIL",
        }
    return out


async def run(args: argparse.Namespace) -> None:
    settings = Settings()
    engine = build_engine(settings.database_url.get_secret_value())
    factory = build_session_factory(engine)
    log = RunLog(started_at=time.strftime("%Y-%m-%dT%H:%M:%S%z"))
    # **Recorded in the log itself, so a smoke number can never be quoted as a
    # measurement.** `--smoke` exists because the harness has to be provable on
    # a toy catalog before it is trusted on the real one, and the only honest
    # way to allow that is to stamp the output rather than to remember.
    log.verdicts["smoke"] = bool(args.smoke)
    log.verdicts["arguments"] = vars(args)
    log.load["before"] = _load_snapshot()

    def _persist(note: str) -> None:
        """Write the run log now, whatever else happens.

        **A phase that raises forty minutes into a quiet window must not take
        the thirty-nine minutes before it with it.** Every phase checkpoints,
        and a crash writes what it had along with the traceback, because the
        alternative is asking for a second quiet window to re-measure numbers
        that were already produced.
        """
        if not args.out:
            return
        log.verdicts["last_checkpoint"] = note
        Path(args.out).write_text(json.dumps(asdict(log), indent=2, default=str), encoding="utf-8")

    try:
        async with factory() as session:
            log.catalog = await catalog_facts(session)
            try:
                log.catalog["frame"] = await check_frame(session)
            except MeasurementRefused as refusal:
                if not args.smoke:
                    raise
                log.catalog["frame"] = {"refused": str(refusal)}
                print(f"SMOKE: frame refusal tolerated -- {refusal}", flush=True)
            await verify_harness(session, log)
            print(json.dumps(log.catalog, indent=2, default=str), flush=True)

            cases = await build_typo_cases(session)
            print(f"typo cases regenerated: {len(cases)} (gate: {GATE_CASES})", flush=True)
            if len(cases) != GATE_CASES:
                print(
                    f"WARNING: regenerated {len(cases)} cases, gate recorded {GATE_CASES}",
                    flush=True,
                )
            if args.sample:
                cases = cases[: args.sample]
            log.catalog["typo_cases"] = len(cases)
            log.catalog["driver_floor"] = await driver_floor(session, max(args.reps, 5))

            if args.indexes:
                _say("indexes: dropping and rebuilding both prefix indexes")
                log.indexes = await measure_indexes(session)
                print(json.dumps(log.indexes, indent=2), flush=True)
                _persist("indexes")

            if args.tier1:
                log.tier1["titles_only"] = await measure_tier1(
                    session, cases, log, reps=args.reps, with_union=False
                )
                log.tier1["union"] = await measure_tier1(
                    session, cases, log, reps=args.reps, with_union=True
                )
                _say("tier1: recall@5 over both configurations")
                log.tier1["recall"] = await measure_tier1_recall(session, cases, with_union=True)
                log.tier1["recall_titles_only"] = await measure_tier1_recall(
                    session, cases, with_union=False
                )
                print(json.dumps(log.tier1, indent=2, default=str), flush=True)
                _persist("tier1")

            if args.tier2:
                log.tier2 = await measure_tier2(session, cases, log, diagnose=args.diagnose)
                print(json.dumps(log.tier2, indent=2, default=str), flush=True)
                _persist("tier2")

            if args.tier2_ab:
                # **The claim being tested is that a btree cannot tax the `%`
                # path, and "cannot" is a claim about the planner rather than
                # about this catalog.** Measured within one run over the same
                # 2,993 cases, one variable: both prefix indexes present, then
                # both dropped. The indexes are rebuilt afterwards, and the
                # rebuild is not optional -- leaving the tree's database
                # without them is how the *next* run measures the wrong thing.
                _say("tier2 A/B: dropping both prefix indexes and re-running")
                for name in (
                    "ix_titles_name_lower_prefix",
                    "ix_title_search_names_name_lower_prefix",
                ):
                    await session.execute(text(f"DROP INDEX IF EXISTS {name}"))
                await session.commit()
                try:
                    log.tier2["without_prefix_indexes"] = await measure_tier2(
                        session, cases, log, diagnose=0
                    )
                finally:
                    _say("tier2 A/B: rebuilding both prefix indexes")
                    await session.execute(
                        text(
                            "CREATE INDEX ix_titles_name_lower_prefix ON titles "
                            "USING btree (lower(name) text_pattern_ops)"
                        )
                    )
                    await session.execute(
                        text(
                            "CREATE INDEX ix_title_search_names_name_lower_prefix "
                            "ON title_search_names USING btree (lower(name) text_pattern_ops)"
                        )
                    )
                    await session.commit()
                print(
                    json.dumps(log.tier2["without_prefix_indexes"], indent=2, default=str),
                    flush=True,
                )
                _persist("tier2_ab")
    except BaseException as failure:
        log.verdicts["crashed"] = f"{type(failure).__name__}: {failure}"
        _persist("crashed")
        raise
    finally:
        await engine.dispose()
    # Sampled after the engine is disposed and every backend is gone, so the
    # "after" reading is taken under the same condition as the "before" one:
    # this harness idle, and whatever else is on the box still running.
    time.sleep(_CPU_SETTLE_SECONDS)
    log.load["after"] = _load_snapshot()
    log.verdicts.update(_verdicts(log))
    before, after = log.load["before"], log.load["after"]
    drift = after["cpu_busy"] - before["cpu_busy"]
    foreign = max(before["processes"]["pytest"], after["processes"]["pytest"])
    log.load["cpu_busy_drift"] = round(drift, 4)
    log.load["foreign_pytest_processes"] = foreign
    # **Absolute, because a box that got *quieter* mid-run is also a box that
    # was not the same box throughout.** A sibling finishing halfway through
    # means the first half was contended, which corrupts a p95 exactly as much
    # as a sibling starting halfway through does. The smoke run that validated
    # this metric drifted **-0.1037** for that reason and a one-sided test
    # would have called it quiet.
    log.load["quiet_enough"] = foreign == 0 and abs(drift) <= _CPU_DRIFT_LIMIT
    # Kept, and demoted. It is the number a reader will look for and it is no
    # longer what decides anything -- so it is printed with the reason.
    log.load["one_minute_loadavg_before_after"] = [before["loadavg"][0], after["loadavg"][0]]
    log.load["loadavg_is_context_not_a_gate"] = (
        "a 40-minute run of continuous querying raises its own one-minute average, so a "
        "before/after load comparison condemns every clean run; the gate is the foreign "
        "pytest census and the idle-sampled CPU drift above"
    )
    print(json.dumps(log.verdicts, indent=2), flush=True)
    if args.out:
        Path(args.out).write_text(json.dumps(asdict(log), indent=2, default=str), encoding="utf-8")
        print(f"\nwrote {args.out}", flush=True)
    if not log.load["quiet_enough"]:
        print(
            f"\nWARNING: the box was not quiet -- {foreign} foreign pytest process(es), "
            f"idle-sampled CPU drift {drift:+.4f} against a limit of "
            f"+/-{_CPU_DRIFT_LIMIT}. "
            "Every number above is a latency; discard and re-run.",
            flush=True,
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Measure both suggest tiers at catalog scale.")
    parser.add_argument("--check-frame", action="store_true", help="verify the frame and stop")
    parser.add_argument("--indexes", action="store_true", help="time and size both prefix indexes")
    parser.add_argument("--tier1", action="store_true", help="bars 1, 2 and 4")
    parser.add_argument("--tier2", action="store_true", help="bar 3")
    parser.add_argument(
        "--tier2-ab",
        action="store_true",
        help="re-run tier 2 with both prefix indexes dropped, then rebuild them",
    )
    parser.add_argument("--all", action="store_true", help="every phase")
    parser.add_argument("--reps", type=int, default=5, help="timed executions per probe")
    parser.add_argument("--diagnose", type=int, default=250, help="misses traced back to a stage")
    parser.add_argument("--sample", type=int, default=0, help="use only the first N typo cases")
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="prove the harness on a toy catalog; tolerates a drifted frame and stamps the log",
    )
    parser.add_argument("--out", default=None, help="write the whole run log here as JSON")
    args = parser.parse_args()
    if args.all:
        args.indexes = args.tier1 = args.tier2 = args.tier2_ab = True
    if args.smoke:
        args.indexes = args.tier1 = args.tier2 = args.tier2_ab = True
        args.sample = args.sample or 24
        args.reps = min(args.reps, 2)
        args.diagnose = min(args.diagnose, 8)
    if args.check_frame:
        args.indexes = args.tier1 = args.tier2 = args.tier2_ab = False
    asyncio.run(run(args))


if __name__ == "__main__":
    main()
