import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  Bell,
  BookOpen,
  Captions,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDashed,
  Clock,
  Copy,
  Database,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileQuestion,
  Film,
  Folder,
  Gauge,
  GitBranch,
  Hammer,
  HardDrive,
  HeartPulse,
  History,
  Home,
  House,
  Image,
  Info,
  Key,
  Layers,
  LibraryBig,
  LayoutDashboard,
  LayoutGrid,
  Link,
  List,
  ListFilter,
  ListVideo,
  Loader,
  Lock,
  Maximize,
  Menu,
  Pause,
  Play,
  Plus,
  Radio,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ScanSearch,
  Search,
  SearchX,
  Server,
  ServerOff,
  Shield,
  SlidersHorizontal,
  Terminal,
  Trash2,
  Tv,
  Unplug,
  User,
  Volume2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Every Lucide glyph this product may use, named exactly as the design system
 * names it. The import list is explicit rather than a dynamic `lucide-react/*`
 * lookup for two reasons the handoff states outright: there must be no
 * third-party runtime (the kits' CDN UMD build is a prototype mechanism), and
 * the bundle must tree-shake — a dynamic namespace import pulls all 1,600 icons
 * into the graph.
 *
 * Adding a glyph is a deliberate act: import it, add the entry, and the name is
 * then type-checked at every call site by `IconName`.
 */
export const ICONS = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  bell: Bell,
  'book-open': BookOpen,
  captions: Captions,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-dashed': CircleDashed,
  clock: Clock,
  copy: Copy,
  database: Database,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-question': FileQuestion,
  film: Film,
  folder: Folder,
  gauge: Gauge,
  'git-branch': GitBranch,
  hammer: Hammer,
  'hard-drive': HardDrive,
  'heart-pulse': HeartPulse,
  history: History,
  home: Home,
  house: House,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  'library-big': LibraryBig,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  link: Link,
  list: List,
  'list-filter': ListFilter,
  'list-video': ListVideo,
  loader: Loader,
  lock: Lock,
  maximize: Maximize,
  menu: Menu,
  pause: Pause,
  play: Play,
  plus: Plus,
  radio: Radio,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'scan-search': ScanSearch,
  search: Search,
  'search-x': SearchX,
  server: Server,
  'server-off': ServerOff,
  shield: Shield,
  'sliders-horizontal': SlidersHorizontal,
  terminal: Terminal,
  'trash-2': Trash2,
  tv: Tv,
  unplug: Unplug,
  user: User,
  'volume-2': Volume2,
  wifi: Wifi,
  'wifi-off': WifiOff,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

/**
 * The six fixed state glyphs. patterns.md §12: colour is never the only carrier
 * of state, so every state is hue **+ icon + word**, and the icon for a given
 * state is the same one everywhere in the product.
 */
export const STATE_ICON = {
  good: 'check-circle',
  warn: 'alert-triangle',
  bad: 'x-circle',
  info: 'info',
  never: 'circle-dashed',
  stale: 'history',
} as const satisfies Record<string, IconName>

export type StateTone = keyof typeof STATE_ICON
