"""Declarative base, engine, and session factory."""

from enum import Enum as PyEnum

from sqlalchemy import Enum as SAEnum
from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

# Ten constraints on the M1 schema before this convention had names Postgres
# generated at CREATE time (titles_pkey, media_items_title_id_fkey, ...)
# rather than names under our control. Every future migration that alters
# one of them -- including the episodes FK the dangling episode_id columns
# are waiting for -- would otherwise have to hardcode a guessed
# autogenerated string, and autogenerate itself can't reliably diff unnamed
# constraints.
#
# For pk/fk/uq/ix, an explicitly-given `name=` is left alone by the
# convention -- it only fills in names for constraints that had none, which
# is exactly what's wanted since this schema's UniqueConstraints and named
# Indexes are already explicitly and deliberately named.
#
# There is deliberately no "ck" key. Unlike the others, SQLAlchemy's naming
# convention machinery treats `%(constraint_name)s` as *always* applying for
# CheckConstraint, even when an explicit name was given -- verified directly:
# with a "ck" key present, this schema's existing, already-fully-formed
# `CheckConstraint(..., name="ck_titles_year_non_negative")` names got
# double-prefixed into `ck_titles_ck_titles_year_non_negative` instead of
# being left alone. Every CheckConstraint in this schema already has an
# explicit, descriptive name (the standard advice to let a naming
# convention synthesize one from columns doesn't fit a CHECK anyway, since
# its condition is an arbitrary SQL expression, not a fixed column list) so
# omitting "ck" costs nothing here and avoids that trap entirely.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all Usher tables."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def build_engine(database_url: str, *, echo: bool = False) -> AsyncEngine:
    # pool_size/max_overflow are hardcoded, not read from usher.config.Settings
    # -- deferred, not designed away. Nothing in M1 has a reason to run more
    # than one process against the same database, so there is no real
    # deployment yet to tune these for. Revisit if/when a milestone adds a
    # second long-running process (e.g. a worker pool) sharing this pool.
    #
    # connect_args={"timeout": 5} bounds asyncpg's own connection-establishment
    # attempt, not query execution. Without it, a connection attempt against
    # an unreachable (not merely refused) host hangs indefinitely -- verified
    # directly against a blackholed address (192.0.2.1, RFC 5737): still
    # blocked after an 8s test budget with no timeout, TimeoutError at 3.00s
    # with connect_args={"timeout": 3}. /health/ready is the one endpoint
    # whose entire job is answering fast, and pool_pre_ping means every other
    # request that checks out a connection pays this same cost on a stale one
    # -- 5s is a generous ceiling for establishing a connection (as opposed to
    # running a query) against a healthy local Postgres.
    return create_async_engine(
        database_url,
        echo=echo,
        pool_pre_ping=True,
        pool_size=10,
        max_overflow=5,
        connect_args={"timeout": 5},
    )


def build_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    return async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)


def enum_column(enum_cls: type[PyEnum], *, length: int) -> SAEnum:
    """A `String`-backed column type for a domain `StrEnum` that round-trips
    to real enum members on read instead of plain `str` — plain
    `mapped_column(String(N))` has no result processor, so `Mapped[SomeEnum]`
    lies: `isinstance(row.kind, TitleKind)` is `False` even though mypy
    believes otherwise (verified).

    `native_enum=False` compiles to `VARCHAR(length)`, identical DDL to the
    `String(length)` it replaces — no native Postgres `CREATE TYPE ... AS
    ENUM`. `create_constraint` defaults to `False` in SQLAlchemy 2.0
    (verified), so no membership CHECK is emitted; Pydantic owns membership
    validation, not the database, matching every other constraint in this
    schema.

    `values_callable` is not optional here: SQLAlchemy's default binds and
    reads back a Python `Enum`'s `.name` (`"MOVIE"`), not its `.value`
    (`"movie"`) — verified directly, including that without this the result
    processor cannot even parse the lowercase values this schema already
    stores. `usher.domain.enums`'s docstring states values are "stable wire
    and storage identifiers"; those identifiers are each member's `.value`.
    """
    return SAEnum(
        enum_cls,
        native_enum=False,
        length=length,
        values_callable=lambda cls: [member.value for member in cls],
    )
